name: PR Template Reminder
on:
  pull_request:
    types: [opened]

jobs:
  remind-template:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/')
    steps:
      - name: Comment on PR
        uses: actions/github-script@v0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Reminder: For release branches, please use the [release PR template](https://github.com/[owner]/[repo]/compare/[branch]?template=release_pr_template.md).'
            })
