name: Update PR Description

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update PR description
      uses: actions/github-script@v5
      with:
        github-token: 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
        script: |
          // Get list of commits in the PR
          const pull_number = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          const listCommitsResponse = await github.rest.pulls.listCommits({
            owner,
            repo,
            pull_number,
          });

          const commits = listCommitsResponse.data.map(commit => commit.commit.message);

          // Construct new PR description
          let newDescription = '### Commits in this PR:\n';
          newDescription += commits.join('\n');

          // Update the PR description
          await github.rest.pulls.update({
            owner,
            repo,
            pull_number,
            body: newDescription,
          });
